using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Mapperize.Generator;

/// <summary>Generates the implementation of one mapper class.</summary>
internal sealed class Emitter
{
    private static readonly SymbolDisplayFormat FullyQualified =
        SymbolDisplayFormat.FullyQualifiedFormat
            .WithMiscellaneousOptions(
                SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
                SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

    private static readonly HashSet<string> KnownLeafTypes = new()
    {
        "System.String", "System.Decimal", "System.DateTime", "System.DateTimeOffset",
        "System.TimeSpan", "System.Guid", "System.Uri", "System.Version",
        "System.DateOnly", "System.TimeOnly", "System.Object",
    };

    private readonly Compilation _compilation;
    private readonly CSharpCompilation? _csharp;
    private readonly INamedTypeSymbol _mapper;
    private readonly Options _options;

    private readonly Dictionary<string, string> _mapMethods = new();   // signature -> method name
    private readonly Queue<MapJob> _pending = new();
    private readonly HashSet<string> _emitted = new();
    private readonly List<Diagnostic> _diagnostics = new();
    private int _helperCounter;

    public Emitter(Compilation compilation, INamedTypeSymbol mapper, AttributeData mapperAttribute)
    {
        _compilation = compilation;
        _csharp = compilation as CSharpCompilation;
        _mapper = mapper;
        _options = Options.Read(mapperAttribute);
    }

    public MapperResult Emit(CancellationToken ct)
    {
        var hint = _mapper.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", string.Empty).Replace('<', '_').Replace('>', '_') + ".g.cs";

        if (_mapper.IsGenericType || _mapper.ContainingType is not null)
        {
            _diagnostics.Add(Diagnostic.Create(Diagnostics.GenericMapperUnsupported,
                _mapper.Locations.FirstOrDefault(), _mapper.Name));
            return new MapperResult(hint, null, _diagnostics.ToImmutableArray());
        }

        // 1. Discover user-declared partial mapping methods and register them as reusable maps.
        var userMethods = new List<UserMethod>();
        foreach (var member in _mapper.GetMembers().OfType<IMethodSymbol>())
        {
            if (member.MethodKind != MethodKind.Ordinary || !member.IsPartialDefinition)
                continue;
            if (member.PartialImplementationPart is not null)
                continue;

            if (member.IsGenericMethod || member.Parameters.Length != 1 || member.ReturnsVoid || member.IsStatic)
            {
                _diagnostics.Add(Diagnostic.Create(Diagnostics.InvalidMapperMethod,
                    member.Locations.FirstOrDefault(), member.Name));
                continue;
            }

            var meta = UserMethod.Read(member);
            userMethods.Add(meta);
            _mapMethods[Key(meta.SourceType, meta.ReturnType)] = member.Name;
        }

        if (userMethods.Count == 0)
            return new MapperResult(hint, null, _diagnostics.ToImmutableArray());

        foreach (var m in userMethods)
            _pending.Enqueue(new MapJob(m.SourceType, m.ReturnType, m.Name, m));

        // 2. Drain the work queue, generating each method body (which may enqueue nested helpers).
        var bodies = new StringBuilder();
        while (_pending.Count > 0)
        {
            ct.ThrowIfCancellationRequested();
            var job = _pending.Dequeue();
            var key = Key(job.Source, job.Target) + "#" + job.MethodName;
            if (!_emitted.Add(key))
                continue;
            EmitMethod(bodies, job);
        }

        var source = Wrap(bodies.ToString());
        return new MapperResult(hint, source, _diagnostics.ToImmutableArray());
    }

    private string Wrap(string bodies)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604");
        sb.AppendLine();

        var ns = _mapper.ContainingNamespace;
        var hasNs = ns is { IsGlobalNamespace: false };
        if (hasNs)
        {
            sb.Append("namespace ").Append(ns!.ToDisplayString()).AppendLine();
            sb.AppendLine("{");
        }

        sb.Append("    ").Append(Accessibility(_mapper.DeclaredAccessibility)).Append(' ')
          .Append("partial ").Append(TypeKeyword(_mapper)).Append(' ').Append(_mapper.Name).AppendLine();
        sb.AppendLine("    {");
        sb.Append(bodies);
        sb.AppendLine("    }");

        if (hasNs)
            sb.AppendLine("}");
        return sb.ToString();
    }

    private void EmitMethod(StringBuilder sb, MapJob job)
    {
        var srcType = job.Source;
        var tgtType = job.Target;
        var srcDisplay = Display(srcType);
        var tgtDisplay = Display(tgtType);
        const string p = "source";
        var paramName = job.User?.ParameterName ?? p;

        // signature
        sb.AppendLine();
        if (job.User is { } um)
            sb.Append("        ").Append(Accessibility(um.Accessibility)).Append(" partial ")
              .Append(Display(um.ReturnType)).Append(' ').Append(job.MethodName)
              .Append('(').Append(Display(um.SourceType)).Append(' ').Append(paramName).AppendLine(")");
        else
            sb.Append("        private ").Append(tgtDisplay).Append(' ').Append(job.MethodName)
              .Append('(').Append(srcDisplay).Append(' ').Append(paramName).AppendLine(")");

        sb.AppendLine("        {");

        if (srcType.IsReferenceType)
            sb.Append("            if (").Append(paramName).Append(" is null) return default;").AppendLine();

        var location = job.User?.Location ?? _mapper.Locations.FirstOrDefault();

        string body;
        if (IsObjectMappable(srcType) && IsObjectMappable(tgtType) && tgtType is INamedTypeSymbol tgtNamed)
        {
            body = BuildConstruction(tgtNamed, srcType, paramName, job.User, location);
        }
        else
        {
            body = Convert(paramName, srcType, tgtType)!;
            if (body is null)
            {
                _diagnostics.Add(Diagnostic.Create(Diagnostics.NoConversion, location,
                    paramName, Display(srcType), "return", Display(tgtType)));
                body = "default(" + tgtDisplay + ")";
            }
        }

        sb.Append("            return ").Append(body).Append(';').AppendLine();
        sb.AppendLine("        }");
    }

    private string BuildConstruction(INamedTypeSymbol targetNamed, ITypeSymbol sourceType, string accessor,
        UserMethod? user, Location? location)
    {
        var readable = ReadableMembers(sourceType);
        var settable = SettableMembers(targetNamed).ToList();
        var ctor = ChooseConstructor(targetNamed, readable, user);

        var ctorCovered = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
        var args = new List<string>();
        if (ctor is { Parameters.Length: > 0 })
        {
            foreach (var prm in ctor.Parameters)
            {
                ctorCovered.Add(prm.Name);
                var expr = ResolveMember(prm.Name, prm.Type, readable, accessor, user, targetNamed, location)
                           ?? "default(" + Display(prm.Type) + ")";
                args.Add(expr);
            }
        }

        var inits = new List<string>();
        foreach (var member in settable)
        {
            if (ctorCovered.Contains(member.Name))
                continue;
            if (user is not null && user.Ignores.Contains(member.Name))
                continue;

            var expr = ResolveMember(member.Name, member.Type, readable, accessor, user, targetNamed, location);
            if (expr is null)
                continue; // ResolveMember already reported the appropriate diagnostic
            inits.Add(member.Name + " = " + expr);
        }

        var tgtDisplay = Display(targetNamed);
        var sb = new StringBuilder();
        sb.Append("new ").Append(tgtDisplay);
        if (args.Count > 0)
            sb.Append('(').Append(string.Join(", ", args)).Append(')');
        else if (inits.Count == 0)
            sb.Append("()");

        if (inits.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("            {");
            for (var i = 0; i < inits.Count; i++)
                sb.Append("                ").Append(inits[i]).AppendLine(i == inits.Count - 1 ? "," : ",");
            sb.Append("            }");
        }
        return sb.ToString();
    }

    /// <summary>Resolves a target member/ctor-param to a source value expression, or null if unmapped.</summary>
    private string? ResolveMember(string targetName, ITypeSymbol targetType,
        Dictionary<string, ISymbol> readable, string accessor, UserMethod? user,
        INamedTypeSymbol owner, Location? location)
    {
        var sourceName = targetName;
        if (user is not null)
        {
            foreach (var rename in user.Renames)
            {
                if (NameEquals(rename.Target, targetName))
                {
                    sourceName = rename.Source;
                    break;
                }
            }
        }

        if (!TryFindMember(readable, sourceName, out var srcMember))
        {
            if (_options.UnmappedBehavior != UnmappedBehavior.Ignore)
            {
                var severity = _options.UnmappedBehavior == UnmappedBehavior.Error
                    ? DiagnosticSeverity.Error
                    : DiagnosticSeverity.Warning;
                _diagnostics.Add(Diagnostic.Create(Diagnostics.UnmappedMember(severity), location,
                    Display(owner), targetName));
            }
            return null;
        }

        var srcMemberType = MemberType(srcMember);
        var srcExpr = accessor + "." + srcMember.Name;
        var conv = Convert(srcExpr, srcMemberType, targetType);
        if (conv is null)
        {
            _diagnostics.Add(Diagnostic.Create(Diagnostics.NoConversion, location,
                srcMember.Name, Display(srcMemberType), targetName, Display(targetType)));
            return null;
        }
        return conv;
    }

    // ---- conversion engine --------------------------------------------------

    private string? Convert(string expr, ITypeSymbol sourceType, ITypeSymbol targetType)
    {
        if (SymbolEqualityComparer.Default.Equals(sourceType, targetType))
            return expr;

        // enums (including nullable enums)
        if (IsEnumLike(sourceType) && IsEnumLike(targetType))
            return ConvertEnum(expr, sourceType, targetType);

        // collections
        if (TryGetElement(sourceType, out var srcElem) && TryGetTargetCollection(targetType, out var tgtElem, out var kind))
            return ConvertCollection(expr, sourceType, srcElem!, tgtElem!, kind);

        // implicit conversion (inheritance, numeric widening, T -> T?, boxing to object, user-defined implicit)
        var classify = _csharp?.ClassifyConversion(sourceType, targetType) ?? default;
        if (classify.IsImplicit && classify.Exists)
            return expr;

        // nullable value unwrap: T? -> something
        var srcNullableUnderlying = NullableUnderlying(sourceType);
        if (srcNullableUnderlying is not null)
        {
            var inner = Convert("(" + expr + ").GetValueOrDefault()", srcNullableUnderlying, targetType);
            if (inner is not null)
                return inner;
        }

        // explicit numeric conversion
        if (classify.Exists && classify.IsNumeric)
            return "(" + Display(targetType) + ")(" + expr + ")";

        // nested complex object mapping
        var srcCore = NullableUnderlying(sourceType) ?? sourceType;
        var tgtCore = NullableUnderlying(targetType) ?? targetType;
        if (IsObjectMappable(srcCore) && IsObjectMappable(tgtCore)
            && srcCore is INamedTypeSymbol srcNamed && tgtCore is INamedTypeSymbol tgtNamed)
        {
            var method = GetOrCreateMap(srcNamed, tgtNamed);
            var needsGuard = sourceType.IsReferenceType || NullableUnderlying(sourceType) is not null;
            var callExpr = NullableUnderlying(sourceType) is not null ? "(" + expr + ").Value" : expr;
            if (needsGuard)
                return expr + " is null ? default(" + Display(targetType) + ") : " + method + "(" + callExpr + ")";
            return method + "(" + callExpr + ")";
        }

        return null;
    }

    private string ConvertEnum(string expr, ITypeSymbol sourceType, ITypeSymbol targetType)
    {
        var srcUnderlying = NullableUnderlying(sourceType);
        var tgtUnderlying = NullableUnderlying(targetType);
        var srcCore = srcUnderlying ?? sourceType;
        var tgtCore = tgtUnderlying ?? targetType;
        var tgtCoreDisplay = Display(tgtCore);

        string Core(string e)
        {
            if (SymbolEqualityComparer.Default.Equals(srcCore, tgtCore))
                return e;
            if (_options.EnumStrategy == EnumStrategy.ByValue)
                return "(" + tgtCoreDisplay + ")(" + e + ")";

            // ByName: switch expression across matching member names.
            var tgtNames = new HashSet<string>(tgtCore.GetMembers().OfType<IFieldSymbol>()
                .Where(f => f.ConstantValue is not null).Select(f => f.Name));
            var arms = new List<string>();
            foreach (var f in srcCore.GetMembers().OfType<IFieldSymbol>().Where(f => f.ConstantValue is not null))
            {
                if (tgtNames.Contains(f.Name))
                    arms.Add(Display(srcCore) + "." + f.Name + " => " + tgtCoreDisplay + "." + f.Name);
            }
            var sb = new StringBuilder();
            sb.Append(e).Append(" switch { ");
            foreach (var arm in arms)
                sb.Append(arm).Append(", ");
            sb.Append("_ => (").Append(tgtCoreDisplay).Append(")(").Append(e).Append(") }");
            return sb.ToString();
        }

        if (srcUnderlying is not null)
        {
            var whenNull = tgtUnderlying is not null ? "(" + Display(targetType) + ")null" : "default(" + tgtCoreDisplay + ")";
            return "(" + expr + ").HasValue ? " + Core("(" + expr + ").Value") + " : " + whenNull;
        }
        return Core(expr);
    }

    private string ConvertCollection(string expr, ITypeSymbol sourceType, ITypeSymbol srcElem,
        ITypeSymbol tgtElem, CollectionKind kind)
    {
        var elemConv = Convert("x", srcElem, tgtElem);
        if (elemConv is null)
            return null!; // caller reports; ConvertCollection is only reached when both are collections

        string sequence = elemConv == "x"
            ? expr
            : "global::System.Linq.Enumerable.Select(" + expr + ", x => " + elemConv + ")";

        var tgtElemDisplay = Display(tgtElem);
        string materialized = kind switch
        {
            CollectionKind.Array => "global::System.Linq.Enumerable.ToArray(" + sequence + ")",
            CollectionKind.HashSet => "new global::System.Collections.Generic.HashSet<" + tgtElemDisplay + ">(" + sequence + ")",
            _ => "global::System.Linq.Enumerable.ToList(" + sequence + ")",
        };

        if (sourceType.IsReferenceType)
            return expr + " is null ? default(" + DisplayCollectionTarget(kind, tgtElemDisplay) + ") : " + materialized;
        return materialized;
    }

    // ---- map registry -------------------------------------------------------

    private string GetOrCreateMap(INamedTypeSymbol source, INamedTypeSymbol target)
    {
        var key = Key(source, target);
        if (_mapMethods.TryGetValue(key, out var existing))
            return existing;

        var name = "Map_" + (++_helperCounter);
        _mapMethods[key] = name;
        _pending.Enqueue(new MapJob(source, target, name, null));
        return name;
    }

    // ---- symbol helpers -----------------------------------------------------

    private IMethodSymbol? ChooseConstructor(INamedTypeSymbol type, Dictionary<string, ISymbol> readable, UserMethod? user)
    {
        var ctors = type.InstanceConstructors
            .Where(c => c.DeclaredAccessibility is Microsoft.CodeAnalysis.Accessibility.Public or Microsoft.CodeAnalysis.Accessibility.Internal)
            .ToList();

        var parameterless = ctors.FirstOrDefault(c => c.Parameters.Length == 0);
        if (parameterless is not null)
            return parameterless;

        foreach (var c in ctors.OrderByDescending(c => c.Parameters.Length))
        {
            if (c.Parameters.All(prm => CanResolve(prm.Name, prm.Type, readable, user)))
                return c;
        }
        return ctors.OrderByDescending(c => c.Parameters.Length).FirstOrDefault();
    }

    private bool CanResolve(string targetName, ITypeSymbol targetType, Dictionary<string, ISymbol> readable, UserMethod? user)
    {
        var sourceName = targetName;
        if (user is not null)
            foreach (var r in user.Renames)
                if (NameEquals(r.Target, targetName)) { sourceName = r.Source; break; }

        if (!TryFindMember(readable, sourceName, out var m))
            return false;
        return Convert("x", MemberType(m), targetType) is not null;
    }

    private Dictionary<string, ISymbol> ReadableMembers(ITypeSymbol type)
    {
        var result = new Dictionary<string, ISymbol>(_options.CaseInsensitive
            ? System.StringComparer.OrdinalIgnoreCase
            : System.StringComparer.Ordinal);

        foreach (var t in SelfAndBases(type))
        {
            foreach (var member in t.GetMembers())
            {
                if (result.ContainsKey(member.Name)) continue;
                switch (member)
                {
                    case IPropertySymbol { GetMethod: not null, IsStatic: false, Parameters.Length: 0 } prop
                        when prop.DeclaredAccessibility == Microsoft.CodeAnalysis.Accessibility.Public:
                        result[prop.Name] = prop;
                        break;
                    case IFieldSymbol { IsStatic: false, IsConst: false } field
                        when field.DeclaredAccessibility == Microsoft.CodeAnalysis.Accessibility.Public:
                        result[field.Name] = field;
                        break;
                }
            }
        }
        return result;
    }

    private IEnumerable<TargetMember> SettableMembers(ITypeSymbol type)
    {
        var seen = new HashSet<string>();
        foreach (var t in SelfAndBases(type))
        {
            foreach (var member in t.GetMembers())
            {
                if (!seen.Add(member.Name)) continue;
                switch (member)
                {
                    case IPropertySymbol { SetMethod: { } set, IsStatic: false, Parameters.Length: 0 } prop
                        when set.DeclaredAccessibility == Microsoft.CodeAnalysis.Accessibility.Public
                             && prop.DeclaredAccessibility == Microsoft.CodeAnalysis.Accessibility.Public:
                        yield return new TargetMember(prop.Name, prop.Type);
                        break;
                    case IFieldSymbol { IsStatic: false, IsConst: false, IsReadOnly: false } field
                        when field.DeclaredAccessibility == Microsoft.CodeAnalysis.Accessibility.Public:
                        yield return new TargetMember(field.Name, field.Type);
                        break;
                }
            }
        }
    }

    private static IEnumerable<ITypeSymbol> SelfAndBases(ITypeSymbol type)
    {
        for (ITypeSymbol? t = type; t is not null && t.SpecialType != SpecialType.System_Object; t = t.BaseType)
            yield return t;
    }

    private bool TryFindMember(Dictionary<string, ISymbol> readable, string name, out ISymbol member)
        => readable.TryGetValue(name, out member!);

    private static ITypeSymbol MemberType(ISymbol s) => s switch
    {
        IPropertySymbol p => p.Type,
        IFieldSymbol f => f.Type,
        _ => throw new System.InvalidOperationException(),
    };

    private static ITypeSymbol? NullableUnderlying(ITypeSymbol type)
        => type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } named
            ? named.TypeArguments[0]
            : null;

    private static bool IsEnumLike(ITypeSymbol type)
    {
        var core = NullableUnderlying(type) ?? type;
        return core.TypeKind == TypeKind.Enum;
    }

    private bool IsMappableComplex(ITypeSymbol type)
    {
        if (type.TypeKind is not (TypeKind.Class or TypeKind.Struct))
            return false;
        if (type.SpecialType != SpecialType.None)
            return false;
        if (type.TypeKind == TypeKind.Enum)
            return false;
        var full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty);
        return !KnownLeafTypes.Contains(full);
    }

    /// <summary>True for a plain object we can construct and map member-by-member (not a collection or enum).</summary>
    private bool IsObjectMappable(ITypeSymbol type)
        => IsMappableComplex(type) && !IsEnumLike(type) && !TryGetElement(type, out _);

    private bool TryGetElement(ITypeSymbol type, out ITypeSymbol? element)
    {
        element = null;
        if (type.SpecialType == SpecialType.System_String)
            return false;
        if (type is IArrayTypeSymbol { Rank: 1 } arr)
        {
            element = arr.ElementType;
            return true;
        }
        var ienum = SelfAndInterfaces(type).FirstOrDefault(i =>
            i.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T);
        if (ienum is not null)
        {
            element = ienum.TypeArguments[0];
            return true;
        }
        return false;
    }

    private bool TryGetTargetCollection(ITypeSymbol type, out ITypeSymbol? element, out CollectionKind kind)
    {
        element = null;
        kind = CollectionKind.List;
        if (type.SpecialType == SpecialType.System_String)
            return false;
        if (type is IArrayTypeSymbol { Rank: 1 } arr)
        {
            element = arr.ElementType;
            kind = CollectionKind.Array;
            return true;
        }
        if (type is not INamedTypeSymbol named || named.TypeArguments.Length != 1)
            return false;

        var def = named.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        element = named.TypeArguments[0];
        switch (def)
        {
            case "global::System.Collections.Generic.HashSet<T>":
            case "global::System.Collections.Generic.ISet<T>":
            case "global::System.Collections.Generic.IReadOnlySet<T>":
                kind = CollectionKind.HashSet;
                return true;
            case "global::System.Collections.Generic.List<T>":
            case "global::System.Collections.Generic.IList<T>":
            case "global::System.Collections.Generic.ICollection<T>":
            case "global::System.Collections.Generic.IEnumerable<T>":
            case "global::System.Collections.Generic.IReadOnlyList<T>":
            case "global::System.Collections.Generic.IReadOnlyCollection<T>":
                kind = CollectionKind.List;
                return true;
            default:
                element = null;
                return false;
        }
    }

    private static IEnumerable<INamedTypeSymbol> SelfAndInterfaces(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named)
            yield return named;
        foreach (var i in type.AllInterfaces)
            yield return i;
    }

    private string DisplayCollectionTarget(CollectionKind kind, string elemDisplay) => kind switch
    {
        CollectionKind.Array => elemDisplay + "[]",
        CollectionKind.HashSet => "global::System.Collections.Generic.HashSet<" + elemDisplay + ">",
        _ => "global::System.Collections.Generic.List<" + elemDisplay + ">",
    };

    private string Display(ITypeSymbol type) => type.ToDisplayString(FullyQualified);

    private string Key(ITypeSymbol source, ITypeSymbol target)
        => source.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + "=>" +
           target.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private bool NameEquals(string a, string b)
        => string.Equals(a, b, _options.CaseInsensitive ? System.StringComparison.OrdinalIgnoreCase : System.StringComparison.Ordinal);

    private static string Accessibility(Microsoft.CodeAnalysis.Accessibility a) => a switch
    {
        Microsoft.CodeAnalysis.Accessibility.Public => "public",
        Microsoft.CodeAnalysis.Accessibility.Internal => "internal",
        Microsoft.CodeAnalysis.Accessibility.Protected => "protected",
        Microsoft.CodeAnalysis.Accessibility.ProtectedOrInternal => "protected internal",
        Microsoft.CodeAnalysis.Accessibility.ProtectedAndInternal => "private protected",
        Microsoft.CodeAnalysis.Accessibility.Private => "private",
        _ => "internal",
    };

    private static string TypeKeyword(INamedTypeSymbol type)
    {
        if (type.IsRecord)
            return type.TypeKind == TypeKind.Struct ? "record struct" : "record";
        return type.TypeKind == TypeKind.Struct ? "struct" : "class";
    }

    // ---- nested types -------------------------------------------------------

    private enum CollectionKind { List, Array, HashSet }

    private readonly record struct MapJob(ITypeSymbol Source, ITypeSymbol Target, string MethodName, UserMethod? User);

    private readonly record struct TargetMember(string Name, ITypeSymbol Type);
}
