using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Mapperize.Generator;

/// <summary>
/// Roslyn incremental source generator that implements the <c>partial</c> mapping methods of
/// every class annotated with <c>[Mapperize.Mapper]</c>. All mapping code is emitted at compile
/// time as direct member assignments — no reflection, no runtime configuration, AOT/trim safe.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class MapperGenerator : IIncrementalGenerator
{
    private const string MapperAttribute = "Mapperize.MapperAttribute";
    private const string MapPropertyAttribute = "Mapperize.MapPropertyAttribute";
    private const string MapperIgnoreTargetAttribute = "Mapperize.MapperIgnoreTargetAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var results = context.SyntaxProvider.ForAttributeWithMetadataName(
            MapperAttribute,
            predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax or StructDeclarationSyntax,
            transform: static (ctx, ct) => Build(ctx, ct));

        context.RegisterSourceOutput(results, static (spc, result) =>
        {
            if (result is null)
                return;

            foreach (var diag in result.Diagnostics)
                spc.ReportDiagnostic(diag);

            if (result.Source is not null)
                spc.AddSource(result.HintName, result.Source);
        });

        // Emit a `services.AddMapperize()` extension, but only when the consumer references
        // Microsoft.Extensions.DependencyInjection — this keeps the package dependency-free for
        // everyone who does not use DI.
        var registrations = results
            .Select(static (r, _) => r?.Registration)
            .Where(static r => r is not null)
            .Collect();

        var hasDependencyInjection = context.CompilationProvider.Select(static (compilation, _) =>
            compilation.GetTypeByMetadataName("Microsoft.Extensions.DependencyInjection.IServiceCollection") is not null);

        context.RegisterSourceOutput(registrations.Combine(hasDependencyInjection), static (spc, pair) =>
        {
            var (regs, hasDi) = pair;
            if (!hasDi)
                return;
            var source = EmitDependencyInjection(regs);
            if (source is not null)
                spc.AddSource("Mapperize.DependencyInjection.g.cs", source);
        });
    }

    private const string ServiceDescriptor = "global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor";
    private const string Lifetime = "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime";
    private const string TryAdd = "global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd";
    private const string GetRequiredService = "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService";

    private static string? EmitDependencyInjection(ImmutableArray<MapperRegistration?> registrations)
    {
        var distinct = registrations
            .Where(r => r is not null)
            .Select(r => r!)
            .GroupBy(r => r.ImplType)
            .Select(g => g.First())
            .OrderBy(r => r.ImplType, System.StringComparer.Ordinal)
            .ToList();

        if (distinct.Count == 0)
            return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Registers Mapperize-generated mappers with the dependency-injection container.</summary>");
        sb.AppendLine("    public static class MapperizeServiceCollectionExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Registers every Mapperize mapper in this assembly. Mappers are stateless, so the");
        sb.AppendLine("        /// default lifetime is <see cref=\"ServiceLifetime.Singleton\"/>.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMapperize(");
        sb.AppendLine("            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        sb.Append("            ").Append(Lifetime).Append(" lifetime = ").Append(Lifetime).AppendLine(".Singleton)");
        sb.AppendLine("        {");

        foreach (var reg in distinct)
        {
            sb.Append("            ").Append(TryAdd).Append("(services, new ").Append(ServiceDescriptor)
              .Append("(typeof(").Append(reg.ImplType).Append("), typeof(").Append(reg.ImplType)
              .AppendLine("), lifetime));");

            if (reg.InterfaceType is not null)
            {
                // The interface resolves to the same concrete registration, so a Singleton mapper is
                // shared between `IFooMapper` and `FooMapper` consumers.
                sb.Append("            ").Append(TryAdd).Append("(services, new ").Append(ServiceDescriptor)
                  .Append("(typeof(").Append(reg.InterfaceType).Append("), static sp => ").Append(GetRequiredService)
                  .Append("(sp, typeof(").Append(reg.ImplType).AppendLine(")), lifetime));");
            }
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static MapperResult? Build(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol mapper)
            return null;

        var emitter = new Emitter(ctx.SemanticModel.Compilation, mapper, ctx.Attributes[0]);
        return emitter.Emit(ct);
    }
}

internal sealed record MapperResult(
    string HintName, string? Source, ImmutableArray<Diagnostic> Diagnostics, MapperRegistration? Registration);

/// <summary>DI registration info for one mapper, collected to emit the <c>AddMapperize</c> extension.</summary>
internal sealed record MapperRegistration(string ImplType, string? InterfaceType);
